### ISSUE TITLE
Update and upstream bchrpc proto doc strings

### ISSUE THREAD

**Issue by 2qx** [2qx/grpc-bchrpc-browser#1]
The bchrpc interface varies considerably in nomenclature and structure from more other toolkits built using separate indexing servers.

In an effort to build a complete client with exhaustive tests, it's useful to have detailed documentation for each specific field and default of the RPCs.

As part of the development of this library, the protobuf file may be further documented, (using the JSON rpc documentation, BU protocol specification, results from testing, and bchd source if necessary).

Documentation should meet the contribution standards of the bchd team for upstreaming with minimal on the part of the bchd team.

An html preview of current work in progress is here: 
https://2qx.github.io/grpc-bchrpc-browser/docs_bchrpc/

The raw proto file is here:
https://github.com/2qx/grpc-bchrpc-browser/blob/master/pb/bchrpc.proto

@cpacia @zquestz, is this something you'all would be interesteed in?

**Comment by zquestz** [comment]
I would love to include these detailed docs. The more the better. =)

**Comment by 2qx** [comment]
Cool!

Let me work out the remainder and finish my test suite, if I misunderstood something I'll find it by doing the tests.

**Comment by 2qx** [comment]
@zquestz, I'm a bit stuck writing a test for the merkle proof, loosly following the example given here: https://bitcoin.stackexchange.com/a/69166

I'm trying to verify the merkle proof for a transaction in [block 150000](https://blockchair.com/bitcoin-cash/block/0000000000000a3290f20e75860d505ce0e948a1d1d846bec7e39015d242884b):
`d97a21cf46fd5afb0bf9ea4237bc4bf5c84e8b47d38d1eee2bbeb5c0f8a1c625` or (`2Xohz0b9WvsL+epCN7xL9chOi0fTjR7uK761wPihxiU=`)

When I request proof of the transaction, I'm get the following list of merkle hashes:
```
ABCD f1b6fe8fc2ab800e6d76ee975a002d3e67a60b51a62085a07289505b8d03f149 
EF   efc2b3db87ff4f00c79dfa8f732a23c0e18587a73a839b7710234583cdd03db9 
G    d97a21cf46fd5afb0bf9ea4237bc4bf5c84e8b47d38d1eee2bbeb5c0f8a1c625 * the transaction
H    ae1e670bdbf8ab984f412e6102c369aeca2ced933a1de74712ccda5edaf4ee57 
IJ   e827331b1fe7a2689fbc23d14cd21317c699596cbca222182a489322ece1fa74 
```

Where the letter annorations on the left are which leafs the hash is the proof for.

The flags are `1101 0110 0000 0...`, or "awA=", or [107,0]

I can't for the life of me figure out how these flags map to the node location, the direction of operations or the fact that the 3rd hash returned is the transaction itself.

I checked bchutil, neutrino, bchwallet but can't seem to find a working example of this field being used or tested. 

I'm not sure how a client without block headers would verify this based on the information being returned.

**Comment by zquestz** [comment]
@cpacia might be a better resource for this. I have not used this field. =)

**Comment by 2qx** [comment]
I think I figured it out by getting the flags for several transactions.

```
A 11111

0 1 ABCDEFGHIJ
1 1 ABCDEFGH IJ
2 1 ABCD EFGH IJ
3 1 AB CD EF GH IJ
4 1 A* B C D E F G H I J
A        e1af205960ae338a37174b407ee71067c3cd7f04d48a5cec7e13f6eccb61dcbc *
B        a314970cd7c647d1cc0a477e1a2122b98205b6924b73001b8dab20ee81c2f4f7
CD       40213c81f059806fb8c1b91d0a7397a57156cfc3a17b71d095c244aafc1eb115
EFGH     8be15fc2ab11ef3e079568d43b2b09ed5a5690fb13ecb1032f7aab99238a1847
IJ       e827331b1fe7a2689fbc23d14cd21317c699596cbca222182a489322ece1fa74

B 111101

0 1 
1 1
2 1
3 1
4 01 A B* C D E F G H I J
A        e1af205960ae338a37174b407ee71067c3cd7f04d48a5cec7e13f6eccb61dcbc
B        a314970cd7c647d1cc0a477e1a2122b98205b6924b73001b8dab20ee81c2f4f7 *
CD       40213c81f059806fb8c1b91d0a7397a57156cfc3a17b71d095c244aafc1eb115
GH       8be15fc2ab11ef3e079568d43b2b09ed5a5690fb13ecb1032f7aab99238a1847
IJ       e827331b1fe7a2689fbc23d14cd21317c699596cbca222182a489322ece1fa74

C 111011

0 1   "
1 1   "
2 1   "
3 01 AB  CD*  EF GH IJ
4 1  A B C* D E F G H I J
AB       a4a2774e14677eaf13a5e8d5f793618ee3b9763ebbd99ac20894b2cea5aa17b7
C        b08eb9dce0452a1b1970c4d29e88bdee07669a2a5d1b08586d7ffa17b2e3f6b5 *
D        958b9e94aea9a485ba494c50fb3192558057f7caed9705d4b11369f071f10642
EFGH     8be15fc2ab11ef3e079568d43b2b09ed5a5690fb13ecb1032f7aab99238a1847
IJ       e827331b1fe7a2689fbc23d14cd21317c699596cbca222182a489322ece1fa74

D 1110101

0 1   "
1 1   "
2 1   "
3 01 AB  CD*  EF GH IJ
4 01 A B C D* E F G H I J
AB       a4a2774e14677eaf13a5e8d5f793618ee3b9763ebbd99ac20894b2cea5aa17b7
C        b08eb9dce0452a1b1970c4d29e88bdee07669a2a5d1b08586d7ffa17b2e3f6b5 
D        958b9e94aea9a485ba494c50fb3192558057f7caed9705d4b11369f071f10642 *
EFGH     8be15fc2ab11ef3e079568d43b2b09ed5a5690fb13ecb1032f7aab99238a1847
IJ       e827331b1fe7a2689fbc23d14cd21317c699596cbca222182a489322ece1fa74

G 1101011

0 1   "
1 1   "
2 01 ABCD       EFGH*  IJ
3 01 AB CD    EF   GH* IJ
4 1  A B C D  E F G* H I J
ABCD     f1b6fe8fc2ab800e6d76ee975a002d3e67a60b51a62085a07289505b8d03f149 
EF       efc2b3db87ff4f00c79dfa8f732a23c0e18587a73a839b7710234583cdd03db9 
G        d97a21cf46fd5afb0bf9ea4237bc4bf5c84e8b47d38d1eee2bbeb5c0f8a1c625 *
H        ae1e670bdbf8ab984f412e6102c369aeca2ced933a1de74712ccda5edaf4ee57 
IJ       e827331b1fe7a2689fbc23d14cd21317c699596cbca222182a489322ece1fa74 
```

**Comment by 2qx** [comment]
see: https://github.com/gcash/bchd/pull/381

**Comment by 2qx** [comment]
https://github.com/gcash/bchd/pull/381

closed out
